Remodeling of Project's CMakeLists.txt
zenitheesc/daemons-framework pull request #1
Opened 2021-10-02 01:37 UTC by CarlosCraveiro

## What type of PR is this?
- [x] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:
This pool request is about the remodeling of Project's CMakeLists.txt.
Basically, its "implements" a high-level CMakeLists.txt.

# Testing
Until the submission of this pool request, tests were done on compilation and execution of a binary (which used Conan libraries) and everything worked fully in an example project. No tests were done in the official directory because many crucial parts of the project were still missing.

2021-10-02 03:10 UTC, Grillo-0 commented on CMakeLists.txt
> +						dbus-handler)
era pra ficar espaçado desse jeito?

2021-10-02 03:10 UTC, Grillo-0 commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
deixe a versão no 3.16.3, pois acho que nem todos tem a 3.18

2021-10-02 03:10 UTC, Grillo-0 commented on CMakeLists.txt
> +)
identação

2021-10-02 03:10 UTC, Grillo-0 commented on CMakeLists.txt
> +                                OUTPUT_NAME "frameworkd")
identação

2021-10-02 03:10 UTC, Grillo-0 commented on CMakeLists.txt
> +	target_link_libraries(frameworkd PRIVATE frameworkd-objlibs)
`frameworkd-objlib` em vez de `frameworkd-objlibs`
```suggestion
	target_link_libraries(frameworkd PRIVATE frameworkd-objlib)
```

2021-10-02 03:29 UTC, Grillo-0 commented on CMakeLists.txt
> +                                OUTPUT_NAME "frameworkd")
O problema dessas identações provavelmente é ter usado tabs em vez de espaços.
Achei esse link falando sobre isso, basicamente vc tem subitituir os tabs por 4 espaços
https://louispetrik.medium.com/github-indentation-2fd44e51a5ea

2021-10-02 03:45 UTC, Grillo-0 requested changes
resolver os comentários anteriores

2021-10-02 10:53 UTC, mairacanal commented on CMakeLists.txt
> +)
Orgulho da minha criança

2021-10-02 10:55 UTC, mairacanal requested changes

2021-10-02 10:55 UTC, mairacanal commented on CMakeLists.txt
> +macro(FRAMEWORKD_ADD_DEPS_FILEPATHS_TO outputList baseDir subDir depsList fileExt)
Será que não dá para diminuir o tamanho do nome dessas macros? Quando você combina elas, fica meio poluido.

2021-10-07 07:25 UTC, CarlosCraveiro commented on CMakeLists.txt
> +						dbus-handler)
Não, mass ja foi corrigido 👍.

2021-10-07 07:26 UTC, CarlosCraveiro commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.18)
Okk 👍.

2021-10-07 07:26 UTC, CarlosCraveiro commented on CMakeLists.txt
> +)
Resolvido.

2021-10-07 07:26 UTC, CarlosCraveiro commented on CMakeLists.txt
> +                                OUTPUT_NAME "frameworkd")
Resolvido.

2021-10-07 07:27 UTC, CarlosCraveiro commented on CMakeLists.txt
> +	target_link_libraries(frameworkd PRIVATE frameworkd-objlibs)
Resolvido 👍.

2021-10-07 07:28 UTC, CarlosCraveiro commented on CMakeLists.txt
> +macro(FRAMEWORKD_ADD_DEPS_FILEPATHS_TO outputList baseDir subDir depsList fileExt)
Dá sim, inclusive já está feito!

2021-10-07 07:31 UTC, Grillo-0 submitted a review, later dismissed

2021-10-07 08:40 UTC, merged