ServiceHandler: Implements methods to change proxys dependencies
zenitheesc/daemons-framework pull request #17
Opened 2021-11-29 05:17 UTC by CarlosCraveiro

## What type of PR is this?
- [x] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Esse pull request foi motivado pela necessidade de implementação dos testes unitátios para as "classes services". 

Durante a tentativa de implementar os testes unitários, senti uma enorme necessidade de fazer mudanças nas dependencias dos proxys contidos no interior do ServiceHandler, mas eu não havia implementado nenhuma maneira de fazer isso. Essa necessidade não apareceu durante a elaboração do ServiceHandler, pois acreditava que que essa dependencias seriam trocadas manualmente por uma outra classe agregada que teria o privilégio de amizade com as classes service. Porém, almejando testes unitários robustos percebi que não haveria mal algum em fornecer métodos públicos no ServiceHandler para fazer essas alterações, visto que estes poderão  ser utilizados também por essa classe que está por vir, eles permitirão testes unitários mais completos e noo pior dos casos, o "user" final do framework não terá acesso à classe ServiceHandler dirertamente pela classe daemon, logo não haverá "riscos".
(Service Handler e a saga continua...)

# Testing

Esse pull request compila e funciona assim como a versão anterior.

2021-11-29 12:07 UTC, mairacanal requested changes
Código ótimo, apenas alguns pequenos comentários relativos a sintaxe.

2021-11-29 12:07 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
>      return requiredState;
```suggestion
    try {
        return m_serviceMap.at(serviceId)->reportState();
    } catch (const std::out_of_range) {
        std::string errorMessage = "Get dependency state request from a not built service! Unknown Service = " + serviceId;

        throw std::invalid_argument(errorMessage);
    }
```

2021-11-29 12:07 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +        errorMessage.append(serviceId);
```suggestion
        std::string errorMessage = "Change dependency state request from a not built service! Unknown Service = " + serviceId;
```

2021-11-29 12:07 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +        errorMessage.append(serviceId);
```suggestion
        std::string errorMessage = "Update request from a not built service! Unknown Service = " + serviceId;
```

2021-11-29 13:57 UTC, Grillo-0 approved these changes, later dismissed
PR muito bom, parabéns 🎉

2021-11-29 17:34 UTC, mairacanal approved these changes

2021-11-29 18:28 UTC, Grillo-0 approved these changes

2021-11-30 20:05 UTC, Math-42 approved these changes
Código ótimo, parabéns!

2021-11-30 20:05 UTC, merged