Fix/change template
zenitheesc/daemons-framework pull request #18
Opened 2022-02-07 18:03 UTC by Grillo-0

## What type of PR is this? (check all applicable)
- [X] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Mudando para o novo template

2022-02-09 15:36 UTC, mairacanal requested changes
"Façam PRs pequenos" - Canal, Maíra
Grillo, Arthur: 26557 linhas, fodase

2022-02-09 15:36 UTC, mairacanal commented on CMakeLists.txt
> +#
Precisa dessas recomendaçöes para Windows?

2022-02-09 15:36 UTC, mairacanal commented on PULL_REQUEST_TEMPLATE.md
> +**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
Esse arquivo é realmente necessário? Considerando que nósvamos ignorar ele KKKK

2022-02-09 15:36 UTC, mairacanal commented on cmake/StandardSettings.cmake
> +option(${PROJECT_NAME}_USE_CATCH2 "Use the Catch2 project for creating unit tests." OFF)
Acho que essa opção pode ser apagada, já que não usamos o Catch2

2022-02-09 15:36 UTC, mairacanal commented on cmake/StaticAnalyzers.cmake
> +endif()
Vamos manter essa opção do CppCheck?

2022-02-09 15:36 UTC, mairacanal commented on docs/html/PULL__REQUEST__TEMPLATE_8md.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
Se o markdown do PR for apagado, naturalmente, esse arquivo também será apagado.

2022-02-10 18:11 UTC, Grillo-0 commented on docs/html/PULL__REQUEST__TEMPLATE_8md.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
noooooooooooosa, a documentação do doxygen tava indo pro repositório 😵‍💫, acho que não queremos isso né? vou colocar essa pasta no .gitignore

2022-02-12 13:15 UTC, mairacanal approved these changes
Bom demais!

2022-02-18 18:14 UTC, Math-42 commented on cmake/SourcesAndHeaders.cmake
> +)
Não tem executável tem?

2022-02-18 18:15 UTC, Grillo-0 commented on cmake/SourcesAndHeaders.cmake
> +)
não tem não

2022-02-18 19:45 UTC, merged