Class/dbus controller
zenitheesc/daemons-framework pull request #2
Opened 2021-10-06 18:28 UTC by Math-42

## What type of PR is this? (check all applicable)
- [X ] ✨ Feature
- [ ] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:
Primeira versão funcional da comunicação via o dbus

2021-10-06 21:21 UTC, Grillo-0 requested changes

2021-10-06 21:21 UTC, Grillo-0 commented on .gitignore
> +tests/test-environment/*
Melhor colocar na build ou fora do repositório

2021-10-15 03:52 UTC, Grillo-0 requested changes

2021-10-15 03:52 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.cpp
> +        throw std::logic_error("methods should be register before finishing the handler");
```suggestion
        throw std::logic_error("Methods should be register before finishing the handler");
```

2021-10-15 03:52 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.cpp
> +    : m_isServer { false } {};
Acho que seria legal colocar os construtores no começo do arquivo por legibilidade

2021-10-15 03:52 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.cpp
> +void DBusHandler::registerMethod(const DBusHandler::Path& path, DBusCallback&& callback)
N seria legal liberar lambdas também em lvalue?
Daria pra fazer isso assim
```suggestion
void DBusHandler::registerMethod(const DBusHandler::Path& path, const DBusCallback& callback)
```

2021-10-15 03:52 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.hpp
> +#include <vector>
headers não utilizados

2021-10-16 02:38 UTC, CarlosCraveiro commented on src/classes/dbus-handler/dbus-handler.hpp
> +        std::string functionality;
Esses membros internos da struct Path não deveriam começar com "m_"? Como m_service, m_objectPath, m_interface, m_functionality?

2021-10-16 02:54 UTC, CarlosCraveiro commented on src/classes/dbus-handler/dbus-handler.hpp
> +#include <vector>
Acho que o header <string> foi utilizado para a definição de strings como membros de classes.

2021-10-16 03:06 UTC, CarlosCraveiro reviewed
Código muito bom!! Fiz alguns comentários/sugestões, mas fora esses quase nada a comentar. Exceto por uma coisa, acho que seria melhor fazer um merge da branch "develop" na "class/dbus-controler" antes de dar merge da class/dbus-controler na develop. 

Isso talvez faça-se necessário, visto a adição do CMakeLists.txt novo na "develop". Mas é só uma sugestão, porque vocês fizeram testes unitários, então era bom verificar se está tudo em ordem quanto ao CMake e suas funcionalidades antes de passar para a "develop".

2021-10-16 19:27 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.hpp
> +#include <vector>
rem razão, eu tirei eles e rodou de boas, provavelmente as bibliotecas do nlhoman e dbus usam, a mesma coisa pro vector. Só o sstream que não é usado mesmo. Os outros headers não são necessários mas acho que é legal deixar.

2021-10-18 19:33 UTC, Math-42 commented on src/classes/dbus-handler/dbus-handler.hpp
> +        std::string functionality;
No caso não, eles são membros da struct expostos para que o usuário os preencha. Acredito que estamos usando essa notação apenas para as variáveis de funcionamento interno da classe.

2021-10-19 15:09 UTC, mairacanal commented on src/classes/dbus-handler/dbus-handler.hpp
> +        std::string functionality;
Reintero o que o Matheus disse.

2021-10-19 15:10 UTC, mairacanal commented on src/classes/dbus-handler/dbus-handler.cpp
> +void DBusHandler::registerMethod(const DBusHandler::Path& path, DBusCallback&& callback)
Não funciona com lvalue nesse caso, já que esse recurso será reutilizado.

2021-10-20 16:56 UTC, Grillo-0 commented on src/classes/dbus-handler/dbus-handler.cpp
> +void DBusHandler::registerMethod(const DBusHandler::Path& path, DBusCallback&& callback)
Acho que entendi, blz então

2021-10-20 16:57 UTC, Grillo-0 approved these changes

2021-10-21 01:43 UTC, CarlosCraveiro approved these changes
Muito bom!! Aprovado!

2021-10-21 11:19 UTC, merged