fix: make m_configHandler public
zenitheesc/daemons-framework pull request #26
Opened 2022-06-29 14:14 UTC by Grillo-0

This needed to be done to make the fkd work properly when a service
needs too access a certain configuration in the json

## What type of PR is this? (check all applicable)
- [ ] ✨ Feature
- [X] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

This needed to be done to make the fkd work properly when a service
needs too access a certain configuration in the json

# Testing

2022-06-29 16:37 UTC, mairacanal requested changes
Also: consertar erro gramatical na mensagem de commit

2022-06-29 16:37 UTC, mairacanal commented on include/frameworkd/classes/daemon/daemon.hpp
> +private:
Não seria mais elegante fazer um getter e um setter?

2022-06-29 17:23 UTC, Grillo-0 commented on include/frameworkd/classes/daemon/daemon.hpp
> +private:
Farei só um getter pois o programador não é previsto sobrescrever o que tem na config

2022-06-29 19:04 UTC, mairacanal requested changes

2022-06-29 19:04 UTC, mairacanal commented on include/frameworkd/classes/daemon/daemon.hpp
> +
Cadê a função?

2022-06-30 01:35 UTC, Grillo-0 commented on include/frameworkd/classes/daemon/daemon.hpp
> +
ops kkkk

2022-06-30 14:58 UTC, mairacanal approved these changes

2022-06-30 14:59 UTC, merged