Class/service
zenitheesc/daemons-framework pull request #6
Opened 2021-10-07 17:59 UTC by CarlosCraveiro

## What type of PR is this? (check all applicable)
- [x] ✨ Feature
- [x] 🐞 Bug Correction
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

# Changes:

Implementando duas classes : IService e Service-Proxy

# Testing

Classes compliladas e testadas. (Aviso! Caso desejem compilar utilizando o CMake do repositório, sugiro adicionarem como dependencias apenas  "service" e "service-proxy", para evitar erros de compilação relacionados aos demais arquivos)

2021-10-08 11:37 UTC, mairacanal requested changes

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-handler/service-handler.hpp
> +		 std::vector<EndpointHandler> endpoints;
O ideal é que atributos de classes sejam privados e também sigam a nomenclatura comum, ou seja, `m_routines`e `m_endpoints`.

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-handler/service-handler.hpp
> +		nlohmann::json registerRoutines(void);
Colocar as trailing functions , considerando a adoção generalizada.

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +        STOPED,
Está escrito errado: `STOPPED`

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    m_dependencies.data = configs; //DETAILS ABOUT DEPENDENCIES
Crie um construtor para o SafeJson e, então, passe o `configs` por meio do construtor padrão do C++

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    };
Criar um construtor

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    static void servicePod(IService& service, Status& status);
Eu achei que o nome `servicePod`é pouco expressivo. Talvez poderia mudar para um nome mais significativo.

2021-10-08 11:37 UTC, mairacanal commented on src/classes/service/service.hpp
> +	explicit IService(std::string serviceId)
Passar por referência no argumento (lembre-se que temos apenas 512mb)

2021-10-08 17:54 UTC, Math-42 requested changes

2021-10-08 17:54 UTC, Math-42 commented on src/classes/service-handler/service-handler.hpp
> + *
Remover esse header

2021-10-08 17:54 UTC, Math-42 commented on src/classes/service/service.cpp
> +*/
remover header

2021-10-08 17:54 UTC, Math-42 commented on src/classes/service/service.hpp
> +	 * 			the user to make the "setup"/configuration
deixar os comentários alinhas com os asteriscos

2021-10-08 17:54 UTC, Math-42 commented on src/classes/service-proxy/service-proxy.hpp
> +    IService& m_innerService;
No desing pattern de proxy, é comum chamar a variável que referencia o objeto real como "real". Sugiro alterar para m_realService.

2021-10-08 17:54 UTC, Math-42 commented on src/classes/service-proxy/service-proxy.cpp
> +    while (status.getState() != Status::STOPED) {
Aqui não seria melhor se fosse ?
```suggestion
    while (status.getState() == Status::RUNNING) 
```
Existem outros estados além desses e o único que permite que ela esteja de fato rodando é o running, não?

2021-10-09 22:47 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    while (status.getState() != Status::STOPED) {
A adoção do `!= Status::STOPPED` tem o objetivo de reservar ao status STOPPED - e somente a ele - o direito de encerrar "rotinas". Assim, a idea era que cada "state" tivesse um objetivo no controle da thread, permitindo ao programador por meio da requisição de status, saber exatamente o que "está acontecendo"/"aconteceu" com cada um de seus "services".

2021-10-12 04:19 UTC, Grillo-0 requested changes

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.hpp
> +    static void servicePod(IService& service, Status& status);
Uma sugestão: `serviceLifeCycle `

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.cpp
> +    std::swap(thread, m_innerThread);
Esse é  o melhor jeito de criar a m_innerThread?
Essa criação dessa thread auxilar me parece estranho.

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-handler/service-handler.hpp
> +};
acertar identação e seguir o estilo Webkit

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.cpp
> +void ServiceProxy::servicePod(IService& service, Status& status)
```suggestion
void ServiceProxy::servicePod()
```

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.cpp
> +    std::thread thread(servicePod, std::ref(m_innerService), std::ref(m_status));
Tente fazer isso
```suggestion
    std::thread thread(&ServiceProxy::servicePod, this);
```
https://stackoverflow.com/questions/17472827/create-thread-inside-class-with-function-from-same-class

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.hpp
> +        MISSINGDEPENDENCIES = 0,
```suggestion
        MISSING_DEPENDENCIES = 0,
```

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service/service.hpp
> +
renomear o arquivo para iservice.hpp

2021-10-12 04:19 UTC, Grillo-0 commented on src/classes/service/service.cpp
> +
precisa desse arquivo já que a classe é puramente virtual?

2021-10-28 00:32 UTC, mairacanal requested changes
Eu não fui capaz de terminar a revisão, mas, no geral, eu recomendo você mesmo dar uma limpeza geral nos arquivos, ver o que não tá sendo utilizado e etc. Além disso, eu acho que alguns arquivos não foram formatados.

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +    for (nlohmann::json::iterator it = servicesConfigs["proxys"].begin(); it != servicesConfigs["proxys"].end(); it++) {
Mudar o loop para uma versão mais moderna com iteradores

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +        for (nlohmann::json::iterator itr = it.value().begin(); itr != it.value().end(); itr++) {
Mudar o loop para uma versão mais moderna com iteradores

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +        m_serviceMap.insert(std::pair<std::string, ServiceProxy*>(userService.m_serviceId, new staticService::Proxy(userService, m_proxyDepsMap.at(userService.m_serviceId))));
Tenta deixar uma linha um pouco menor, para melhorar a legibilidade.

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +    for (itr = m_serviceMap.begin(); itr != m_serviceMap.end(); itr++) {
Mudar o loop para uma versão mais moderna com iteradores

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +    for (itr = m_serviceMap.begin(); itr != m_serviceMap.end(); itr++) {
Mudar o loop para uma versão mais moderna com iteradores

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +    std::map<std::string, ServiceProxy*>::iterator itr;
Apaga essa variável

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.hpp
> +//private:
Apagar o comentário

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-handler/service-handler.hpp
> +    explicit ServiceHandler(nlohmann::json servicesConfigs);
Coloca o construtor no começo para facilitar a leitura.

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    for (itr = depsMap.begin(); itr != depsMap.end(); itr++) {
Mudar o loop

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +        //m_depsMap.emplace(itr->first, Dependencie(itr->second, Status::UNKNOWN));
Apagar o comentário

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +
Apaga a linha

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    enum stateT { MISSING_DEPENDENCIES = 0,
Péssimo nome de enum

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    m_upperProxy->changeState(MISSING_DEPENDENCIES);
Colocar o `Status::`no MISSING_DEPENDENCIES

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    for (itr = m_proxyConfigs.m_depsMap.begin(); itr != m_proxyConfigs.m_depsMap.end(); itr++) {
Mudar o loop

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    (noMissingDependencies) ? m_status->allFine() : m_status->somethingIsMissing();
Não colocar operador ternário perdido no meio do nada

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +        std::cout << "ERROR!! This was not supose to happen!! - Static Service" << std::endl;
Lançar exceção

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    (noMissingDependencies) ? m_status->allFine() : m_status->somethingIsMissing();
Cópia de código da outra função `autoUpdate`

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    };
Mais uma função repetida

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +
Função repetida

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    }
Coloca o construtor em cima

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    enum proxyT { STATIC_SERVICE = 0,
Outro nome de enum pouco sugestivo

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +        struct Dependencie {
A forma correta de escrita é `Dependency`

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +    ProxyConfigs m_proxyConfigs;
Retirar coisas temporárias

2021-10-28 00:32 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +
Vazio

2021-11-09 22:15 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +        //m_depsMap.emplace(itr->first, Dependencie(itr->second, Status::UNKNOWN));
Resolvido!!

2021-11-11 00:30 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +
Não entendi tão bem, mass apliquei o ClangFormat.

2021-11-11 02:39 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.hpp
> +    explicit ServiceHandler(nlohmann::json servicesConfigs);
Feito!!

2021-11-11 02:41 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +    enum stateT { MISSING_DEPENDENCIES = 0,
Nome de enum alterado para state_t, quis manter o "t"zinho, acho que deixa mais claro que trata-se de um "tipo artificial".

2021-11-11 02:41 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    (noMissingDependencies) ? m_status->allFine() : m_status->somethingIsMissing();
Alterado para um if/else statement!!

2021-11-11 02:41 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    m_upperProxy->changeState(MISSING_DEPENDENCIES);
Feito!!

2021-11-11 02:43 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    (noMissingDependencies) ? m_status->allFine() : m_status->somethingIsMissing();
Retirado dos proxys filhos e implementado no proxy pai, aka Service Proxy!!

2021-11-11 02:46 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    };
Essa função foi melhorada com o uso de smart pointers, mass quanto à implementação de uma função comum no proxy pai para ser utilizada pelos proxys filhos, esta exigiria de uma reformulação do uso dos states pelas classes service... podemos considerar como um "Problema em aberto da computação".

2021-11-11 02:46 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +    enum proxyT { STATIC_SERVICE = 0,
Nome trocado para proxy_t.

2021-11-11 02:47 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +        struct Dependencie {
Erro gramatical corrigido!!

2021-11-11 03:58 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +
Função implementada no proxy pai, aka ServiceProxy, e retirada dos proxys filhos.

2021-11-11 03:58 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +    }
Feito!!

2021-11-11 03:58 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +        std::cout << "ERROR!! This was not supose to happen!! - Static Service" << std::endl;
Feito!!

2021-11-11 23:40 UTC, Grillo-0 requested changes

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/iservice/iservice.hpp
> +#include <iostream>
Esse iostream desnecessário

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/iservice/iservice.hpp
> +    //	DBusHandler::DBusHandler m_dbus;
Linha comentada

2021-11-11 23:40 UTC, Grillo-0 commented on CMakeLists.txt
> +    routine-service-proxy
Apesar de esse cmake morrer daqui a pouco, eu não acho legal deixar alguns arquivo comentados. Então só deixa os arquivos novos, também a identação ta errada

2021-11-11 23:40 UTC, Grillo-0 commented on CMakeLists.txt
> +    #locked-storage
mesma coisa

2021-11-11 23:40 UTC, Grillo-0 commented on CMakeLists.txt
> +    #service
mesma coisa

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/iservice/iservice.hpp
> +
Espaço desnecessário

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-handler/service-handler.cpp
> +                std::make_unique<StaticServiceProxy>(userService, m_proxyDepsMap.at(userService.m_serviceId))));
Identação

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-handler/service-handler.cpp
> +                std::make_unique<RoutineServiceProxy>(userService, m_proxyDepsMap.at(userService.m_serviceId))));
Identação

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-handler/service-handler.cpp
> +
Espaço desnecessário

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-handler/service-handler.hpp
> +
Esse Tester n é do seu "unit test" que nem vai ser subido?

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.cpp
> +#include <iostream>
Include denecessário

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.hpp
> +    friend class Tester;
Já falado

2021-11-11 23:40 UTC, Grillo-0 commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    friend class Tester;
Já falado

2021-11-11 23:42 UTC, mairacanal requested changes
Passar clang-format em tudo

2021-11-11 23:42 UTC, mairacanal commented on src/classes/iservice/iservice.hpp
> +    }
```suggestion
    explicit StaticService(std::string serviceId)
        : IService(serviceId) {};
```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/iservice/iservice.hpp
> +    }
Mudança análoga pode ser feita em todo o arquivo.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    // Expose/Hide the endpoint on the DBUS and THEN..
Não coloque comentário aqui. Faça o Javadoc apropriado da função.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN..
Não coloque comentário aqui. Faça o Javadoc apropriado da função.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_updateMtx);
```suggestion
    const std::lock_guard<std::mutex> lock{m_updateMtx};
```

Em geral, isso melhora a legibilidade do código.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/routine-service-proxy/routine-service-proxy.hpp
> +        }
```suggestion
        RoutineState(state_t state, RoutineServiceProxy& upperProxy)
            : m_upperProxy(upperProxy)
            , ServiceState(state) {};
```

Aplicar de forma análoga em todo arquivo

2021-11-11 23:42 UTC, mairacanal commented on src/classes/iservice/iservice.hpp
> +#include <string>
O uso dessas bibliotecas é realmente necessário?

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +}
Não rodou o clang-format nesse trecho

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +#include <iostream>
Não adicionar bibliotecas no cpp

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN..
Não coloque comentário aqui. Faça o Javadoc apropriado da função.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN...
Não coloque comentário aqui. Faça o Javadoc apropriado da função.

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    , ServiceProxy(realService, STATIC_SERVICE, depsMap)
```suggestion
StaticServiceProxy::StaticServiceProxy(StaticService& realService, std::map<std::string, ServiceState::state_t> depsMap)
    : m_runnedOnce{false}
    , ServiceProxy{realService, STATIC_SERVICE, depsMap}
```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_stateMtx);
```suggestion
    const std::lock_guard<std::mutex> lock{m_stateMtx};
```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +        }
```suggestion
        StaticState(state_t state, StaticServiceProxy& upperProxy)
            : ServiceState{state}
            , m_upperProxy{upperProxy} {};
```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    bool m_runnedOnce;
Não deixe atributos públicos

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +
Apagar linha

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_stateMtx);
```suggestion
    const std::lock_guard<std::mutex> lock{m_stateMtx};
```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-proxy/service-proxy.hpp
> +
```suggestion
        explicit ServiceState(state_t state)
            : m_state{state} {};

```

2021-11-11 23:42 UTC, mairacanal commented on src/classes/service-handler/service-handler.hpp
> +#include "../iservice/iservice.hpp"
Essa biblioteca é realmente necessária?

2021-11-11 23:45 UTC, Grillo-0 commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    , ServiceProxy(realService, STATIC_SERVICE, depsMap)
Isso é só estético? Sempre tive essa duvida

2021-11-12 20:11 UTC, Math-42 requested changes

2021-11-12 20:11 UTC, Math-42 commented on src/classes/iservice/iservice.hpp
> +    /* Id of the service */
comentário desnecessário visto que o nome da variável já é auto explicativo

2021-11-12 20:11 UTC, Math-42 commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +        throw std::logic_error("Routine Services should not have other States!");
Isso é muito improvável de acontecer, sendo assim poderia lançar algo como unknow status, e imprimir o valor que foi lido, apenas para elucidar melhor o log de erros.

2021-11-12 20:11 UTC, Math-42 commented on src/classes/service-proxy/service-proxy.cpp
> +    return (nlohmann::json) { { "serviceId", m_realServiceId }, { "State", currStatus } };
isso tudo não poderia ser resumido em uma linha só? 
```suggestion
    return (nlohmann::json) { { "serviceId", m_realServiceId }, { "State", checkState(); } };
```

2021-11-12 20:11 UTC, Math-42 commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +        throw std::logic_error("Static Services should not have other States!");
Ver a observação que fiz anteriormente no arquivo semelhante.

2021-11-12 20:11 UTC, Math-42 commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    bool m_runnedOnce;
Na verdade ele está como protected, porem na ordem acabou ficando confuso, eu sugiro que coloque ele antes da declaração das classes.

2021-11-16 01:14 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +#include <iostream>
Resolvido!!

2021-11-16 01:18 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +    //	DBusHandler::DBusHandler m_dbus;
Resolvido!!

2021-11-16 01:18 UTC, CarlosCraveiro commented on CMakeLists.txt
> +    routine-service-proxy
Resolvido!!

2021-11-16 01:18 UTC, CarlosCraveiro commented on CMakeLists.txt
> +    #locked-storage
Resolvido!!

2021-11-16 01:33 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.cpp
> +                std::make_unique<StaticServiceProxy>(userService, m_proxyDepsMap.at(userService.m_serviceId))));
Resolvida!!

2021-11-16 01:33 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +
Resolvido!!

2021-11-16 01:33 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.cpp
> +                std::make_unique<RoutineServiceProxy>(userService, m_proxyDepsMap.at(userService.m_serviceId))));
Resolvido!!

2021-11-16 01:33 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.hpp
> +
Sim, apagado!

2021-11-16 01:34 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +    }
Mudança análoga aplicada em todo os arquivos!!

2021-11-16 01:34 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN..
Feito!!

2021-11-16 01:34 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_updateMtx);
Legibilidade melhorada!!

2021-11-16 01:35 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.hpp
> +        }
Aplicado!!

2021-11-16 01:35 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +#include <iostream>
Removidas!!

2021-11-16 01:35 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.cpp
> +
Resolvido!!

2021-11-16 01:35 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +#include <iostream>
De fato!!

2021-11-16 01:36 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +    // Expose/Hide the endpoint on the DBUS and THEN..
Feito!!

2021-11-16 01:37 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +#include <string>
Pelo menos uma, mantive só a string por motivos de clareza.

2021-11-16 01:38 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN..
Feito!!

2021-11-16 01:38 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    // Unexpose/Hide the endpoint on the DBUS and THEN...
Feito!!

2021-11-16 01:38 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    , ServiceProxy(realService, STATIC_SERVICE, depsMap)
Resolvido!!

2021-11-16 01:38 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +        }
Resolvido!!

2021-11-16 01:42 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +
Resolvido!!

2021-11-16 01:43 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    bool m_runnedOnce;
Feito!!

2021-11-16 01:43 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_stateMtx);
Feito!!

2021-11-16 01:43 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock(m_stateMtx);
Resolvido!!

2021-11-16 01:43 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +
Resolvido!!

2021-11-16 01:44 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.hpp
> +#include "../iservice/iservice.hpp"
Por motivos de clareza sim, pois nela são definido os services

2021-11-16 01:44 UTC, CarlosCraveiro commented on src/classes/iservice/iservice.hpp
> +    /* Id of the service */
Resolvido!!

2021-11-16 01:44 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.cpp
> +        throw std::logic_error("Routine Services should not have other States!");
Feito!!

2021-11-16 01:45 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    return (nlohmann::json) { { "serviceId", m_realServiceId }, { "State", currStatus } };
Resolvido!!

2021-11-16 01:45 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +        throw std::logic_error("Static Services should not have other States!");
Resolvido!!

2021-11-16 11:20 UTC, mairacanal requested changes
Em geral, tá excelente. Só tenho esses comentários pequenos dessa vez. Uma última pergunta: tu passou o valgrind nisso?

2021-11-16 11:20 UTC, mairacanal commented on src/classes/service-handler/service-handler.cpp
> +
Remover essa linha

2021-11-16 11:20 UTC, mairacanal commented on src/classes/routine-service-proxy/routine-service-proxy.hpp
> +    std::mutex m_updateMtx;
Coloca as variáveis antes das classes, com o objetivo de melhorar a legibilidade

2021-11-16 11:20 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +#include <memory>
Essa biblioteca é necessária? Eu não vi nenhum `unique_ptr` nessa classe.

2021-11-16 11:20 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    StaticServiceProxy(StaticService& realService, std::map<std::string, ServiceState::state_t> depsMap);
Faltou importar a biblioteca `map`

2021-11-16 11:20 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock { m_stateMtx };
Faltou importar a biblioteca `mutex`

2021-11-16 13:48 UTC, Grillo-0 requested changes
Código muito bom, só alguns comentários de legibilidade

2021-11-16 13:48 UTC, Grillo-0 commented on CMakeLists.txt
> -	locked-storage
Não deletar

2021-11-16 13:48 UTC, Grillo-0 commented on CMakeLists.txt
> -	service
Não deletar

2021-11-16 13:48 UTC, Grillo-0 commented on CMakeLists.txt
> +    routine-service-proxy
indentação

2021-11-16 13:48 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.cpp
> +    m_depsMap[dependencieId].m_currState = currState;
Acho que seria melhor usar o .at() em vez da sobrecarga de operador

2021-11-16 13:48 UTC, Grillo-0 commented on src/classes/service-proxy/service-proxy.hpp
> +#include <iostream>
iostream não me parece necessário

2021-11-16 14:06 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +#include <memory>
Então, o uso de unique pointers está no .cpp dela, mais precisamente nos "std::make_unique" do método changeState, deixei no header a inclusão mesmo só sendo usada no .cpp, pois foi pedido para não incluir as bibliotecas no .cpp.

2021-11-16 14:11 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    m_depsMap[dependencieId].m_currState = currState;
Qual o motivo exatamente?

2021-11-16 17:17 UTC, mairacanal commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +#include <memory>
Deixei passar o `make_unique`. Perdão, desconsidere essa sugestão.

2021-11-16 17:21 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	service
Service precisa apagar sim na real, pq esse arquivo acho que não faz mais sentido com o projeto.

2021-11-16 17:27 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	locked-storage
Então...mass se eu não apagar, preciso deixar comentada as linhas

2021-11-16 17:28 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	locked-storage
Caso contrário, o cmake não gera os arquivos, pq ele não acha os arquivos do dbus-handler e locked-storage

2021-11-16 17:29 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	locked-storage
config-handler ele achou, mass acho inclusive que essa classe não existe mais/ foi substituída por outra.

2021-11-16 17:29 UTC, CarlosCraveiro commented on CMakeLists.txt
> +    routine-service-proxy
Não tinha visto a nota de identação na requisição de mudanças passada, dsclp.

2021-11-16 17:30 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +#include <iostream>
Verdade, parei para pensar e não tenho como justificar ele.

2021-11-16 17:36 UTC, CarlosCraveiro commented on src/classes/service-handler/service-handler.cpp
> +
Feito!!

2021-11-16 17:36 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.hpp
> +    StaticServiceProxy(StaticService& realService, std::map<std::string, ServiceState::state_t> depsMap);
Feito!!

2021-11-16 17:36 UTC, CarlosCraveiro commented on src/classes/static-service-proxy/static-service-proxy.cpp
> +    const std::lock_guard<std::mutex> lock { m_stateMtx };
Feito!!

2021-11-16 17:37 UTC, CarlosCraveiro commented on src/classes/routine-service-proxy/routine-service-proxy.hpp
> +    std::mutex m_updateMtx;
Feito!!

2021-11-16 17:37 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.hpp
> +#include <iostream>
Removido!!

2021-11-16 18:06 UTC, mairacanal approved these changes, later dismissed
Já deu de reclamar do código né

Toma meu Approve aí e seja feliz.

2021-11-16 18:18 UTC, Math-42 submitted a review, later dismissed

2021-11-16 18:34 UTC, CarlosCraveiro commented on src/classes/service-proxy/service-proxy.cpp
> +    m_depsMap[dependencieId].m_currState = currState;
Feito!!

2021-11-16 18:34 UTC, CarlosCraveiro commented on CMakeLists.txt
> +    routine-service-proxy
Resolvido

2021-11-16 18:35 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	locked-storage
Resolvido!!

2021-11-16 18:36 UTC, CarlosCraveiro commented on CMakeLists.txt
> -	service
Deletado só service que não está mais entre nós!

2021-11-16 18:39 UTC, Grillo-0 approved these changes
Finalmente tudo ta certo 🥳

2021-11-16 18:41 UTC, mairacanal approved these changes

2021-11-16 18:41 UTC, merged